name: flutter_ume_kits

packages:
  - packages/**
  - example

scripts:
  analyze:
    exec: dart analyze .
  get:
    exec: flutter pub get
  test:
    exec: flutter test
  format:
    exec: dart format --set-exit-if-changed .

sdkPath: auto