name: flutter_ume_kit_designer_check
description: UI check tool for designer.
version: 1.0.0
homepage: https://github.com/cfug/flutter_ume_kit

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: ^1.1.2
  image_picker: ^0.8.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
