name: flutter_ume_kit_dio
description: Dio kit for flutter_ume.
version: 2.0.0+3
homepage: https://github.com/cfug/flutter_ume_kits

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: ^1.1.2

  dio: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
